### ISSUE TITLE
Keep getting this error any time I try to import anything.

### ISSUE THREAD

**Issue by TechtackIDK** [REDxEYE/SourceIO#330]
![image](https://github.com/user-attachments/assets/3496ee26-13d6-4521-a3e5-4f463db62432)

I don't understand what any of it means but I always get this error regardless of what I'm trying to import, be it map or model from any game anywhere. I used to be able to import models from this directory (and other directories), but now they just don't work anymore for no apparent reason.

**Comment by REDxEYE** [comment]
That's very weird. This should not never happened. There is no way for NoneType to appear there. Please re-install addon and try again

**Comment by TechtackIDK** [comment]
Reinstalled twice - no dice. The model I'm trying to open is from a custom search path from Source Filmmaker, but again this directory _used_ to work, but hasn't for the past while.

**Comment by REDxEYE** [comment]
Can you please upload full console log?

**Comment by TechtackIDK** [comment]
Registered nodes
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/usermod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/smut")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/bladesymphony")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/ep2_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/episodic_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dinodday")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/ep2_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/episodic_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc1")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc1")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/stanleyparable")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/usermod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/smut")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/usermod/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/bladesymphony/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dinodday/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dod/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc1/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc2/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/stanleyparable/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies/gameinfo.txt")
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:49
Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 54, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 24, in import_model
    steam_id = content_provider.get_steamid_from_asset(model_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\manager.py", line 68, in get_steamid_from_asset
    if provider := child.get_steamid_from_asset(asset_path):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 35, in get_steamid_from_asset
    if self.check(asset_path):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 20, in check
    if mount.check(filepath):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\providers\loose_files.py", line 12, in check
    if filepath.is_absolute():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_absolute'

**Comment by REDxEYE** [comment]
I've added additional log message. Can you download new version and try with it and post new logs here?

**Comment by TechtackIDK** [comment]
Registered nodes
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/usermod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/smut")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/bladesymphony")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/ep2_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/episodic_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dinodday")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/ep2_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/episodic_workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc1")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc1")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/stanleyparable")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/platform")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/usermod")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/smut")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/usermod/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: LooseFilesContentProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/workshop")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/bladesymphony/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dinodday/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/dod/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/hl2/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/left4dead2_movies/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc1/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/portal2_dlc2/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/stanleyparable/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf/gameinfo.txt")
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/tf_movies/gameinfo.txt")
[INFO]--[MDL loader:import_model]: Trying to load model: E:/SteamLibrary/steamapps/common/SourceFilmmaker/game/smut/models/MMD/jyb_unknown/busty female base.mdl
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:49
Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 54, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\blender_bindings\models\__init__.py", line 25, in import_model
    steam_id = content_provider.get_steamid_from_asset(model_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\manager.py", line 68, in get_steamid_from_asset
    if provider := child.get_steamid_from_asset(asset_path):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 35, in get_steamid_from_asset
    if self.check(asset_path):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 20, in check
    if mount.check(filepath):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO-master\library\shared\content_manager\providers\loose_files.py", line 12, in check
    if filepath.is_absolute():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_absolute'

**Comment by REDxEYE** [comment]
I cannot reproduce it or find a root cause of it. Try different version of blender as last resort

**Comment by TechtackIDK** [comment]
Works fine in 4.0, not 4.1 or later, also noticed an oddity between the versions, 4.0 import prompt looks like this:
![image](https://github.com/user-attachments/assets/4c166e5b-9c8b-4336-9272-b527ebb94e6d)

4.1 and onward looks like this:
![image](https://github.com/user-attachments/assets/3fe252b8-cdbf-4eda-aa54-ced71e1a8ae4)

I'm probably overthinking and it's meant to be like that, but I'm curious if there's some connection.

**Comment by REDxEYE** [comment]
Different versions. GoldSrc/Source model was introduced in latest version

**Comment by Darvan76** [comment]
Yeah this happening to me too, i think ill use 4.0 as a workaround

**Comment by REDxEYE** [comment]
So it only happens on 4.2?

**Comment by TechtackIDK** [comment]
4.1 as well. Works fine on 4.0, possibly 3.x.

**Comment by REDxEYE** [comment]
I just tested in 4.2 and i'm unable to reproduce it. Model imported just fine for me

**Comment by REDxEYE** [comment]
Should be fixed now. Will work in blender 4.0-4.2
