### ISSUE TITLE
Material import failure

### ISSUE THREAD

**Issue by NewSummo** [REDxEYE/SourceIO#363]
AttributeError: 'Material' object has no attribute 'shadow_method'

![Image](https://github.com/user-attachments/assets/37404dd4-531d-45f0-959f-b800027a3133)

**Comment by REDxEYE** [comment]
SourceIO [5.4.6](https://github.com/REDxEYE/SourceIO/releases/tag/5.4.6.fix) is not yet compatible with blender 4.3. 
Please update to [develop version](https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip) or downgrade to 4.2

**Comment by NewSummo** [comment]
k thanks for fast response!

**Comment by NewSummo** [comment]
Development version has same issue

**Comment by REDxEYE** [comment]
Are you sure it's the same?

**Comment by REDxEYE** [comment]
Developer version is working with 4.3, tested by many users

**Comment by NewSummo** [comment]
Yes I uninstalled 5.4.6 and installed dev version. Dev version still shows as 5.4.6.

**Comment by NewSummo** [comment]
Downloaded from link provided

**Comment by REDxEYE** [comment]
Have you restarted blender after updating addon?

**Comment by NewSummo** [comment]
Yes

**Comment by REDxEYE** [comment]
Well, try completely removing the addon and installing dev version i linked

**Comment by NewSummo** [comment]
That's exactly what I did

**Comment by REDxEYE** [comment]
I bumped the version number, re-download and install it
You should get 5.4.7. If it's not 5.4.7 then you're doing something wrong

**Comment by NewSummo** [comment]
Rebooting windows worked

**Comment by REDxEYE** [comment]
I have no idea how you manage to do that. Blender restart is enough...

**Comment by NewSummo** [comment]
I updated recently, maybe that's why. Anyway, the addon seems to work now. Thanks for assistance!
